**Python Libraries: Numpy**

 *collection of modules that are linked together is also known as a Python library. It has code bundles that can be used again and again in different programs. For programmers, it makes Python programming easier and simpler. Since then, we will not need to compose the same code for various projects.*

In [2]:
import numpy as np

In [3]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [4]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# Create a of size 10
v = np.zeros(10)
v[4] = 1
print(v)
print(type(v))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [6]:
v = np.arange(50)     #. arange -> range
print(v)
v = v[::-1]
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [7]:
vector = np.array([1,2,3])
print(vector)

print(vector[::-1])

vector2 = np.arange(20)
print(vector2)



[1 2 3]
[3 2 1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


**2D Array in NUMPY**

In [8]:
v = np.arange(9).reshape(3,3)   #. 2D data
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
# Function: Non-Zero, nonzero()
nz = np.nonzero([1,0,0,0,3,0,0,0,3,0,2])
print(nz)                                   # Returns indexes of non-zero values

(array([ 0,  4,  8, 10]),)


In [10]:
# Identity Matrix

v = np.eye(5)
print(v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [11]:
v = np.random.random(10)
print(v)

[0.5904229  0.15101163 0.68765594 0.23613477 0.3505516  0.6190361
 0.8190805  0.1090786  0.79662511 0.75114492]


*Random Functions in Python*

*       *np.random -> NumPuy submodule ro random number generation*
*   *random() -> function that generates random numbers from a uniform distribution over the interval[0,1)*
*   *(2,2,2) -> single tuple specifying the shape of the desired 3D array. -> create a 3D array with dimensions 2 x 2 x 2*





In [12]:
v = np.random.random((2,2,2))
print(v)

[[[0.69274077 0.01367434]
  [0.18496117 0.06531442]]

 [[0.17077019 0.96547495]
  [0.93034467 0.93183443]]]


In [13]:
v = np.random.random((5,5,5)) #. -> 5D array dimension of 5 x 5 x5
print(v)

[[[3.63778265e-01 1.69229585e-01 7.68244015e-01 6.75939484e-01
   5.77123768e-01]
  [5.79730100e-01 2.56328885e-01 8.57094360e-01 1.36038851e-01
   7.97639131e-01]
  [6.22677201e-01 6.53831322e-01 1.40351092e-01 5.40802010e-01
   3.92500276e-02]
  [8.91798341e-02 5.59331037e-01 1.70459354e-01 6.42353040e-01
   3.72952966e-01]
  [1.60159719e-01 5.78034371e-01 7.72580109e-01 3.27921959e-01
   3.40844067e-01]]

 [[1.77562073e-01 7.45079387e-01 8.90741785e-01 6.20852923e-01
   7.87664222e-01]
  [7.71457945e-01 2.16791803e-01 6.93631430e-01 4.25665377e-01
   2.87981424e-01]
  [1.98735566e-01 7.33835085e-01 5.56716864e-01 8.53158797e-01
   9.18249069e-01]
  [3.74868087e-01 1.35822266e-01 5.37960168e-01 2.72470453e-01
   3.33209958e-01]
  [6.30982381e-01 6.99235285e-02 5.66615663e-01 2.31567764e-01
   7.10346812e-01]]

 [[7.71770714e-01 6.31576176e-01 6.31741201e-01 2.09682715e-01
   8.98778273e-01]
  [4.94444623e-01 2.94655766e-01 5.26893834e-01 9.60176948e-01
   8.71494540e-01]
  [5.8061614

In [14]:
#. Funcitons: min and max
v = np.random.random((10,10))
#print(v)
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

0.9890231310625175 0.001795725252203506


In [15]:
v = np.random.random(30)
v_mean = v.mean()
print(v_mean)


0.4754880535455507


In [16]:
v = np.ones((10,10))
print(v)
v[1:-1, 1:-1] = 0
print(v)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
# Create a 10 x 10 matrix all with the values of 0 and replace inner values with 1

v = np.zeros((10,10))
print("Before \n" , v, "\n")
v[1:-1, 1:-1] = 1
print("After: \n", v)

Before 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 

After: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
v = np.ones((5,5))
print(v)
print()
v = np.pad(v, pad_width = 1 , mode="constant", constant_values = 9)   # Padding -> Adding extra layer with border
print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[9. 9. 9. 9. 9. 9. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 9. 9. 9. 9. 9. 9.]]


In [19]:
'''
Notes:
'''
# nan =/= zero(0)
#. Dont compare with 0

In [20]:
print('1.',0 * np.nan)
print('2.',np.nan == np.nan)
print('3.',np.inf > np.nan)
print('4.',np.nan - np.nan)
print('5.',0.3 == 3 * 0.1)


1. nan
2. False
3. False
4. nan
5. False


In [21]:
print(0.1 * 3)

0.30000000000000004


In [22]:
# Exploring with nan

#nan in arrays

v = np.array([1,2,3, np.nan, 5])
print(v)
isnan = np.isnan(v) # Identifies nan in an array


[ 1.  2.  3. nan  5.]


In [23]:
# Two arrays with nan in them and adding the arrays

v1 = np.array([5,6,np.nan,np.nan,np.nan])
v2 = np.array([2,3,10,np.nan,3])

v_add = v1+v2
print(v_add)
# Adding any value to nan will make it nan

v_substract = v1-v2
print(v_substract)
# if one of the values is nan, the output value will be nan

v_multiply = v1*v2
print(v_multiply)
# Multiplication of any number will also result in the result to be nan



[ 7.  9. nan nan nan]
[ 3.  3. nan nan nan]
[10. 18. nan nan nan]


**Create a 5 X 5 matrix with values 1,2,3,4 diagonally**

In [24]:
#. Steps: create a identity matrix with eye()function
#.        get a diagonal values array (1,2,3,4,5)
#.        multiply the identity matrix with diagonal values

id_matrix = np.eye(5,5)
diagonal_values = np.array([1,2,3,4,5])
output_matrix = id_matrix * diagonal_values

print(id_matrix)        #. Identity Matrix
print()
print(output_matrix)    #. After multiplication

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


**Print 1,2,3,4 just below the diagonal**

In [25]:
# below the diagonal
import numpy as np

Z = np.diag(1+np.arange(4), k=-1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [26]:
#. Checkerboard Pattern Printer

Z = np.zeros((8,8), dtype = int)
Z[1::2, ::2] = 1  # SECOND ROW: INDEX 1: 1,3,5,7 change to 1, SECOND COLUMN STARTING FROM FIRST COLUMN(INDEX 0). COLUMN 0,2,4,6
Z[::2, 1::2] = 1  # Every SECOND ROW STARTING FROM FIRST ROW(INDEX 0), AND EVERY SECOND COLUMN STARTING FROM THE SECOND COLUMN(INDEX 1)
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [27]:
#. Consider a (6,7,8) shape array, what is the x,y,z of the 100th element?
#. function: unravel()
#. np.unravel_index() : convert a flat index into a tuple of indices in a multi-dimensional array.
#. This program: i. find the tuple of indices that corresponds to the flat index 100 in a 3-D array with dimensions(6,7,8).

print(np.unravel_index(100,(6,7,8)))

# This means that in a 3D array with dimensions(6,7,8) the element at flat index 100 is located at position(1,5,4) when you consider each dimensions separatly.

(1, 5, 4)


In [41]:
# Class Assignment
# Create a checkerboard 8 x 8 matrix using the tile function.

# Single 2 x 2 checkerboard
ck_board = np.array([[0,1], [1,0]])
print(ck_board)

# Using tile function in numpy to create a 8 x 8 checkerboard matrix
ck_board = np.tile(ck_board, (4,4))
print(ck_board)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [29]:
# Tuesday 8/29

In [30]:
import numpy as np
lst1 = [11,22,33,44,55,66,77,88,99,110]
arr1 = np.array(lst1)     # Converting a list to an array
print(type(arr1))

<class 'numpy.ndarray'>


In [31]:
tup1 = (12,23,34,45,56,67,78,89,90)
arr2 = np.array(tup1)     # Converting a tuple to an array
print(type(arr2))

<class 'numpy.ndarray'>


In [32]:
set1 = {1,2,3,4,5,6,6,7, True, False, 'Python','Programming'}
arr3 = np.array(set1)
arr3

array({False, 1, 2, 3, 4, 5, 6, 7, 'Programming', 'Python'}, dtype=object)

In [33]:
dict1 = {'a':[1,2,3,4,5,0],'b':(True, False),'c': 'Python','d': 'Programming'}
arr3 = np.array(set1)
arr3

array({False, 1, 2, 3, 4, 5, 6, 7, 'Programming', 'Python'}, dtype=object)

In [34]:
str1 = "Python Programming"
arr5 = np.array(str1)
print(arr5)

Python Programming


**Class Assignment**

In [35]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10])  # 1D Array
print(arr1d)
arr1d.ndim          # To Check the dimension of the numpy array

[ 1  2  3  4  5  6  7  8  9 10]


1

In [36]:
arr2d = np.array([[1,2,3,4,5],[9,8,7,6,5]])   # 2D Array
print(arr2d)
arr2d.ndim          # -> should be 2

[[1 2 3 4 5]
 [9 8 7 6 5]]


2

In [37]:
arr3d = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])     # 3D Array
print(arr3d)
arr3d.ndim

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]]


3

In [42]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([
    [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],
    [[[11, 12, 13], [14, 15, 16]], [[11, 12, 13], [14, 15, 16]]]
    ])

print(a.ndim)       # 0D
print(b.ndim)       # 1D
print(c.ndim)       # 2D
print(d.ndim)       # 3D
print(e.ndim)       # 4D

0
1
2
3
4
