<a href="https://colab.research.google.com/github/r7humagai/DataScienceBootCamp/blob/main/Class%20Notes/Python_LibraryDS_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Python Libraries: Numpy**

 *collection of modules that are linked together is also known as a Python library. It has code bundles that can be used again and again in different programs. For programmers, it makes Python programming easier and simpler. Since then, we will not need to compose the same code for various projects.*

In [ ]:
import numpy as np

In [ ]:
print(np.__version__)
np.show_config()

1.23.5
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [ ]:
v = np.zeros(10)
print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
# Create a of size 10
v = np.zeros(10)
v[4] = 1
print(v)
print(type(v))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [ ]:
v = np.arange(50)     #. arange -> range
print(v)
v = v[::-1]
print(v)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [ ]:
vector = np.array([1,2,3])
print(vector)

print(vector[::-1])

vector2 = np.arange(20)
print(vector2)



[1 2 3]
[3 2 1]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


**2D Array in NUMPY**

In [ ]:
v = np.arange(9).reshape(3,3)   #. 2D data
print(v)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# Function: Non-Zero, nonzero()
nz = np.nonzero([1,0,0,0,3,0,0,0,3,0,2])
print(nz)                                   # Returns indexes of non-zero values

(array([ 0,  4,  8, 10]),)


In [ ]:
# Identity Matrix

v = np.eye(5)
print(v)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
v = np.random.random(10)
print(v)

[0.5904229  0.15101163 0.68765594 0.23613477 0.3505516  0.6190361
 0.8190805  0.1090786  0.79662511 0.75114492]


*Random Functions in Python*

*       *np.random -> NumPuy submodule ro random number generation*
*   *random() -> function that generates random numbers from a uniform distribution over the interval[0,1)*
*   *(2,2,2) -> single tuple specifying the shape of the desired 3D array. -> create a 3D array with dimensions 2 x 2 x 2*





In [ ]:
v = np.random.random((2,2,2))
print(v)

[[[0.69274077 0.01367434]
  [0.18496117 0.06531442]]

 [[0.17077019 0.96547495]
  [0.93034467 0.93183443]]]


In [ ]:
v = np.random.random((5,5,5)) #. -> 5D array dimension of 5 x 5 x5
print(v)

[[[3.63778265e-01 1.69229585e-01 7.68244015e-01 6.75939484e-01
   5.77123768e-01]
  [5.79730100e-01 2.56328885e-01 8.57094360e-01 1.36038851e-01
   7.97639131e-01]
  [6.22677201e-01 6.53831322e-01 1.40351092e-01 5.40802010e-01
   3.92500276e-02]
  [8.91798341e-02 5.59331037e-01 1.70459354e-01 6.42353040e-01
   3.72952966e-01]
  [1.60159719e-01 5.78034371e-01 7.72580109e-01 3.27921959e-01
   3.40844067e-01]]

 [[1.77562073e-01 7.45079387e-01 8.90741785e-01 6.20852923e-01
   7.87664222e-01]
  [7.71457945e-01 2.16791803e-01 6.93631430e-01 4.25665377e-01
   2.87981424e-01]
  [1.98735566e-01 7.33835085e-01 5.56716864e-01 8.53158797e-01
   9.18249069e-01]
  [3.74868087e-01 1.35822266e-01 5.37960168e-01 2.72470453e-01
   3.33209958e-01]
  [6.30982381e-01 6.99235285e-02 5.66615663e-01 2.31567764e-01
   7.10346812e-01]]

 [[7.71770714e-01 6.31576176e-01 6.31741201e-01 2.09682715e-01
   8.98778273e-01]
  [4.94444623e-01 2.94655766e-01 5.26893834e-01 9.60176948e-01
   8.71494540e-01]
  [5.8061614

In [ ]:
#. Funcitons: min and max
v = np.random.random((10,10))
#print(v)
v_max, v_min = v.max(), v.min()
print(v_max, v_min)

0.9890231310625175 0.001795725252203506


In [ ]:
v = np.random.random(30)
v_mean = v.mean()
print(v_mean)


0.4754880535455507


In [ ]:
v = np.ones((10,10))
print(v)
v[1:-1, 1:-1] = 0
print(v)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# Create a 10 x 10 matrix all with the values of 0 and replace inner values with 1

v = np.zeros((10,10))
print("Before \n" , v, "\n")
v[1:-1, 1:-1] = 1
print("After: \n", v)

Before 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 

After: 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
v = np.ones((5,5))
print(v)
print()
v = np.pad(v, pad_width = 1 , mode="constant", constant_values = 9)   # Padding -> Adding extra layer with border
print(v)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[9. 9. 9. 9. 9. 9. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 1. 1. 1. 1. 1. 9.]
 [9. 9. 9. 9. 9. 9. 9.]]


In [ ]:
'''
Notes:
'''
# nan =/= zero(0)
#. Dont compare with 0

In [ ]:
print('1.',0 * np.nan)
print('2.',np.nan == np.nan)
print('3.',np.inf > np.nan)
print('4.',np.nan - np.nan)
print('5.',0.3 == 3 * 0.1)


1. nan
2. False
3. False
4. nan
5. False


In [ ]:
print(0.1 * 3)

0.30000000000000004


In [ ]:
# Exploring with nan

#nan in arrays

v = np.array([1,2,3, np.nan, 5])
print(v)
isnan = np.isnan(v) # Identifies nan in an array


[ 1.  2.  3. nan  5.]


In [ ]:
# Two arrays with nan in them and adding the arrays

v1 = np.array([5,6,np.nan,np.nan,np.nan])
v2 = np.array([2,3,10,np.nan,3])

v_add = v1+v2
print(v_add)
# Adding any value to nan will make it nan

v_substract = v1-v2
print(v_substract)
# if one of the values is nan, the output value will be nan

v_multiply = v1*v2
print(v_multiply)
# Multiplication of any number will also result in the result to be nan



[ 7.  9. nan nan nan]
[ 3.  3. nan nan nan]
[10. 18. nan nan nan]


**Create a 5 X 5 matrix with values 1,2,3,4 diagonally**

In [ ]:
#. Steps: create a identity matrix with eye()function
#.        get a diagonal values array (1,2,3,4,5)
#.        multiply the identity matrix with diagonal values

id_matrix = np.eye(5,5)
diagonal_values = np.array([1,2,3,4,5])
output_matrix = id_matrix * diagonal_values

print(id_matrix)        #. Identity Matrix
print()
print(output_matrix)    #. After multiplication

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


**Print 1,2,3,4 just below the diagonal**

In [ ]:
# below the diagonal
import numpy as np

Z = np.diag(1+np.arange(4), k=-1)
print(Z)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#. Checkerboard Pattern Printer

Z = np.zeros((8,8), dtype = int)
Z[1::2, ::2] = 1  # SECOND ROW: INDEX 1: 1,3,5,7 change to 1, SECOND COLUMN STARTING FROM FIRST COLUMN(INDEX 0). COLUMN 0,2,4,6
Z[::2, 1::2] = 1  # Every SECOND ROW STARTING FROM FIRST ROW(INDEX 0), AND EVERY SECOND COLUMN STARTING FROM THE SECOND COLUMN(INDEX 1)
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#. Consider a (6,7,8) shape array, what is the x,y,z of the 100th element?
#. function: unravel()
#. np.unravel_index() : convert a flat index into a tuple of indices in a multi-dimensional array.
#. This program: i. find the tuple of indices that corresponds to the flat index 100 in a 3-D array with dimensions(6,7,8).

print(np.unravel_index(100,(6,7,8)))

# This means that in a 3D array with dimensions(6,7,8) the element at flat index 100 is located at position(1,5,4) when you consider each dimensions separatly.

(1, 5, 4)


In [ ]:
# Class Assignment
# Create a checkerboard 8 x 8 matrix using the tile function.

# Single 2 x 2 checkerboard
ck_board = np.array([[0,1], [1,0]])
print(ck_board)

# Using tile function in numpy to create a 8 x 8 checkerboard matrix
ck_board = np.tile(ck_board, (4,4))
print(ck_board)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
# Tuesday 8/29

In [ ]:
import numpy as np
lst1 = [11,22,33,44,55,66,77,88,99,110]
arr1 = np.array(lst1)     # Converting a list to an array
print(type(arr1))

<class 'numpy.ndarray'>


In [ ]:
tup1 = (12,23,34,45,56,67,78,89,90)
arr2 = np.array(tup1)     # Converting a tuple to an array
print(type(arr2))

<class 'numpy.ndarray'>


In [ ]:
set1 = {1,2,3,4,5,6,6,7, True, False, 'Python','Programming'}
arr3 = np.array(set1)
arr3

array({False, 1, 2, 3, 4, 5, 6, 7, 'Programming', 'Python'}, dtype=object)

In [ ]:
dict1 = {'a':[1,2,3,4,5,0],'b':(True, False),'c': 'Python','d': 'Programming'}
arr3 = np.array(set1)
arr3

array({False, 1, 2, 3, 4, 5, 6, 7, 'Programming', 'Python'}, dtype=object)

In [ ]:
str1 = "Python Programming"
arr5 = np.array(str1)
print(arr5)

Python Programming


**Class Assignment**

In [ ]:
arr1d = np.array([1,2,3,4,5,6,7,8,9,10])  # 1D Array
print(arr1d)
arr1d.ndim          # To Check the dimension of the numpy array

[ 1  2  3  4  5  6  7  8  9 10]


1

In [ ]:
arr2d = np.array([[1,2,3,4,5],[9,8,7,6,5]])   # 2D Array
print(arr2d)
arr2d.ndim          # -> should be 2

[[1 2 3 4 5]
 [9 8 7 6 5]]


2

In [ ]:
arr3d = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])     # 3D Array
print(arr3d)
arr3d.ndim

[[[1 2 3]
  [2 3 4]]

 [[3 4 5]
  [4 5 6]]]


3

In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
e = np.array([
    [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],
    [[[11, 12, 13], [14, 15, 16]], [[11, 12, 13], [14, 15, 16]]]
    ])

print(a.ndim)       # 0D
print(b.ndim)       # 1D
print(c.ndim)       # 2D
print(d.ndim)       # 3D
print(e.ndim)       # 4D

0
1
2
3
4


----
**Numpy Practice Session from freeCodeCamp**

----

**Numpy Introduction**

List vs Numpy:

Why is Numpy faster than list?


*   Numpy array is a collection of similar data-types that are densely packed in memory. A Python list can have different data-types, which puts lots of extra constraints while doing computation on it.
*   Numpy is able to divide a task into multiple subtasks and process them parallelly.
*   Numpy functions are implemented in C. Which again makes it faster compared to Python Lists.

------

**Numpy Features:**


*   SIMD Vector Processing : Single Instruction Multiple Data
    
    -> SIMD architecrture executes the same instrucrtion on multiple data sets simultaneously. This means that all processors in a SIMD system perform the same operation on different pieces of data.
*   Effective Cache Utilization

-----

**Applications of NumPy**


*     Mathematics(MATLAB replacement)
*     Plotting(Matplotlib)
*     Backend(Pandas, Connect4, Digital Photography)
*     Machine Learning
----

**Load in Numpy**

--------

In [ ]:
import numpy as np

*The Basics*

In [ ]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [ ]:
b = np.array([[9.0, 8.0, 7.9],[5.2, 6.7,3.2]])    # 2-Dimensional List
b

array([[9. , 8. , 7.9],
       [5.2, 6.7, 3.2]])

In [ ]:
# Get Dimension
a.ndim      # gives out the dimension eg. 1D, 2D

1

In [ ]:
b.ndim      # -> 2D

2

In [ ]:
print(a.shape)     # To see how many rows and columns are there
print(b.shape)

(3,)
(2, 3)


In [ ]:
# Get datatypes of array
print(a.dtype)   # int
print(b.dtype)   # float


int64
float64


In [ ]:
c = np.array(['Roshan', 'Data' , 'Scientist'])      # String data in numpy array
print(c)
print(c.dtype)

['Roshan' 'Data' 'Scientist']
<U9


In [ ]:
# Specify data type during initialization

a = np.array([1,2,3], dtype = 'int16')
a

array([1, 2, 3], dtype=int16)

        int16 vs int64.  -> Memory Efficiency:
        int 16 uses 2 bytes(16 bits) of memory per element, while int64 uses 8 bytes(64) of memory per element


In [ ]:
# Get size

print(a.itemsize)       # Since array a has data type int16, and int16 uses 2 bytes of memory per element, the itemsize should be 2
print(b.itemsize)       # Since array b contains float elements and floats are bigger than int
print(b.dtype)

2
8
float64


In [ ]:
# Get total size
a.nbytes

6

        Note: Specify datatypes while initializing array to be more efficient
        eg. a = np.array([1,2,3], dtype = 'int16')

**Accessing/Changing specific elements, row, columns, etc**

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])      # 2 X 7 array
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get the shape (2,7)
a.shape

(2, 7)

In [ ]:
# Get the specific element [r,c] -> Indexing starts at 0
print(a[1, 5])
print(a[1, -4])     # Also works, negative notation

13
11


In [ ]:
# Get a specific row
print(a[0])       # First row

# Get a specific column
print(a[:,2])     # print all the rows, index 2 colmns

[1 2 3 4 5 6 7]
[ 3 10]


In [ ]:
# Other indexing

a[0, 6:1:-2]


array([7, 5, 3])

In [ ]:
# Changing the value inside the array
# Change '12' to 24
print(a)
a[1, 4] = 24

print()

print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 24 13 14]]


In [ ]:
# Task: Change it back to 12 using negative indexing
a[-1, -3] = 12
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


**3D Examples**

In [ ]:
b = np.array([[[1,2],[3,4]], [[5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific elements for 3D arrays(Method: Work outside in)

print(b[0,1,0])       # -> 3
print(b[1, 0, 1])     # -> 6

3
6


In [ ]:
# Replacement using index

print(b)
print("\nAfter replacement: ")
b[:,1,:] = ([9,10],[11,12])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

After replacement: 
[[[ 1  2]
  [ 9 10]]

 [[ 5  6]
  [11 12]]]


----

**Initializing Different Types of Array**

----

In [ ]:
# All 0s Matrix

np.zeros(2)         # np.zeros((rows))

array([0., 0.])

In [ ]:
# All 1s Matrix

np.ones((2,3))        # np.ones((rows, columns))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Any other number
print(np.full((2,2), 99))      # np.full((rows, columns) , specific_number)

# Specifying the datatypes


[[99 99]
 [99 99]]


In [ ]:
a = np.ones((4,2,6), dtype = 'int64')     # Specifying the data type
print(a)
print(a.dtype)

[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]]]
int64


In [ ]:
np.full((2,3,4),12, dtype = 'int32')

array([[[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]], dtype=int32)

In [ ]:
# Any other number using full_like
print(a.shape)
print()
print(np.full_like(a, 4))

(4, 2, 6)

[[[4 4 4 4 4 4]
  [4 4 4 4 4 4]]

 [[4 4 4 4 4 4]
  [4 4 4 4 4 4]]

 [[4 4 4 4 4 4]
  [4 4 4 4 4 4]]

 [[4 4 4 4 4 4]
  [4 4 4 4 4 4]]]


In [ ]:
#

In [ ]:
# Random decimal numbers
np.random.randint(-1,6, size = (3,3))

array([[2, 3, 1],
       [0, 1, 1],
       [0, 4, 1]])

In [ ]:
# Random Integer Values
np.random.randint(7, size = (3,3))

array([[5, 2, 3],
       [5, 0, 2],
       [0, 5, 6]])

In [ ]:
# Creating a identity Matrix
np.identity(5)

np.identity(5, dtype = 'int32')     # Specifying the datatype


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int32)

In [ ]:
np.identity(3)      # identity matrix of 3 rows and 3 columns

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeat an array using axis = 0 -> rows
arr_2d = np.array([[1,2,3]])
print(arr_2d)
# repeat three times
r1 = np.repeat(arr_2d,3, axis = 0) # axis = 0 -> rows
print(r1)

[[1 2 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# Repeat an array using axis=1, using columns
arr_2d = np.array([[1,2,3,4,5]])
print(arr_2d)
# repeat three times
r1 = np.repeat(arr_2d,3, axis = 0) # axis = 1 -> columns
print(r1)

[[1 2 3 4 5]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


        In order for matrix multiplication to be defined,
        the number of columns in the first matrix
        must be equal to
        the number of rows in the second matrix.


          Matrix Multiplication in Python
          res = np.dot(mat1,mat2)

In [ ]:
# Practice question
# Create a matrix with 1 in the border and 0 everywhere else, except the mid-value will be 9
'''
Approach:
1. Make a matrix1 size 5 X 5 with all 1s
2. Make a matrix2 size 3 X 3 with all 0s
3. Change the value of matrix2[1][1] = 9
3. replace the inner value of first matrix1 with second matrix using slicing
'''

matrix1 = np.ones((5,5))
matrix2 = np.zeros((3,3))
matrix3 = np.full(1, 9)

print(matrix1)
print(matrix2)
print(matrix3)
matrix2[1,1] = matrix3
print(matrix2)
matrix1[1:4,1:4] = matrix2
print("Final:\n",matrix1)



[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[9]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
Final:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


        Be careful when copying arrays!!!
      

In [ ]:
# Copying arrays
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(b)

[100   2   3]


**Mathematics Opearations in Numpy**

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
# Direcly Manipulate the elements of array using Mathematical functions

print(a + 2)
print(a - 2)
print(a * 2)
print(a / 2)
print(a ** 2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [ ]:
a = np.array([1,2,3,4])
b = np.array([1,0,1,0])
a + b
print(a+b)      # Two arrays can be summed up


[2 2 4 4]


In [ ]:
# Take trigonometric functions:
a = [0,30,45,60,90]
np.cos(a)
np.sin(a)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

Math Routine Docs: https://numpy.org/doc/stable/reference/routines.math.html

----

**Linear Algebra**

In [ ]:
a = np.full((2,3), 1)
print(a)
print()
b = np.full((3,2), 2)
print(b)

[[1 1 1]
 [1 1 1]]

[[2 2]
 [2 2]
 [2 2]]


In [ ]:
# Matrix Multiplication
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [ ]:
# Determinant of a matrix
c = np.identity(3)
np.linalg.det(c)

1.0

Other Linear Algebra resources:
https://numpy.org/doc/stable/reference/routines.linalg.html

----

**Statistics**

In [ ]:
stats = np.array([[7,2,3],[4,5,6]])
stats

array([[7, 2, 3],
       [4, 5, 6]])

In [ ]:
# Take the min
print(np.min(stats))
print(np.min(stats, axis = 0))      # minimum of each column
print(np.min(stats, axis = 1))      # minimum of each row


2
[4 2 3]
[2 4]


In [ ]:
# Take the max
print(np.max(stats))
print(np.max(stats, axis = 0))      # maxiumum of each column
print(np.max(stats, axis = 1))      # maximum of each row

7
[7 5 6]
[7 6]


In [ ]:
# Take the mean
print(np.mean(stats))
print(np.mean(stats, axis = 0))     # Mean of each column
print(np.mean(stats, axis = 1))     # Mean of each row

4.5
[5.5 3.5 4.5]
[4. 5.]


**Reorganizing Arrays**


In [ ]:
# Reshaping Arrays
# Requirements: before and after arrays should have the same amount of values

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)
print()
after = before.reshape((2,2,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertical Stacks: vertifcally stacking matrices or vectors
# Important: Dimensions

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

vstack_result = np.vstack([v1,v2, v2,v1])
print(vstack_result)
print(type(vstack_result))


[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]
<class 'numpy.ndarray'>


In [ ]:
# Horizantal Stack

h1 = np.array([1,2,3,4])
h2 = np.array([5,6,7,8])

horizantal_stack = np.hstack([v2, v1, v1, v2])
print(horizantal_stack)
print(type(horizantal_stack))

[5 6 7 8 1 2 3 4 1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


**Miscellaneous**

-----

**Load Data from File**

In [ ]:
# Case: Loading data from file using numpy(not using panda dframe)


In [ ]:
filedata = np.genfromtxt('data.txt', delimiter = ',')

print(filedata)
print(type(filedata))     # Print data type of the whole text
print(filedata.dtype)     # Print data type of data inside


[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
<class 'numpy.ndarray'>
float64


In [ ]:
#Change the data type to int32
filedata = filedata.astype('int32')
print(filedata)

print(type(filedata))     # Print data type of the whole text
print(filedata.dtype)     # Print data type of data inside

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
<class 'numpy.ndarray'>
int32


**Boolean Masking & Advanced Indexing**

In [ ]:
filedata > 50     # Checks boolean data for specific location

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
filedata[filedata > 50]     # Only grab the values that satisfy the boolean conditions

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [ ]:
# Indexing with a List in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
z = (a[[1,2,8]])
print(z)


[2 3 9]


           numpy.any() function is used to check
           if any element in a given array evaluates to True
           along a specified axis or in the entire array.

           numpy.any(a, axis=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)


In [ ]:
filedata = np.genfromtxt('data.txt', delimiter = ',')
filedata = filedata.astype('int32')

print(filedata)

print()
np.any(filedata > 50, axis = 0)   # Along the column
print()
np.any(filedata > 50, axis = 1)   # Along the rows

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]




array([ True,  True,  True])

In [ ]:
#Compare with numpy.all -> only return True if ALL elements satisfy the condition, here > 50

np.all(filedata > 50, axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [ ]:
((filedata > 50) & (filedata < 100))        # Double Condition

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
(~(filedata > 50) & (filedata < 100))     # '~' Reverse

array([[ True,  True,  True,  True, False, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

**Practice Questions**

In [ ]:
# 1. Import the numpy package under the name np
import numpy as np

In [ ]:
# 2. Print the numpy version and the configuration
print(np.__version__)   # version
print(np.show_config()) # configuration

In [ ]:
# 3. create a null vector of size 10
vector1 = np.zeros(10)
print(vector1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#4. How to find the memory size of any array
vector1.nbytes    # bytes

80

In [ ]:
#. Compute the min/max for each row for a Numpy 2D array

# Generating the array
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

# Computing max/min for each row

np.apply_along_axis(lambda x: np.min(x)/np.max(x), arr = a, axis = 1)

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]


array([0.44444444, 0.125     , 0.5       , 1.        , 0.11111111])

In [ ]:
np.apply_along_axis(lambda row: print(row), arr=a , axis= 1)

[9 9 4]
[8 8 1]
[5 3 6]
[3 3 3]
[2 1 9]


array([None, None, None, None, None], dtype=object)